title: Prolike.io
description: 'We run a frank and transparent business, teaching the Yipees the ins and outs of being a professional consultant, freelancer, innovator or entrepreneur'
author: Prolike
url: https://stage.prolike.io
paginate: 24
paginate_path: "/stories/page:num/"

logo: /img/seo_img.png
image: /img/seo_img.png

social:
  name: Prolike
  links: https://www.linkedin.com/company/prolike/

sass:
  style: compressed

highlighter: rouge
exclude:
  - "*README.md"
  - bower_components
  - node_modules
  - gulpfile.js
  - LICENSE
  - package.json
  - package-lock.json
timezone: Europe/Copenhagen
markdown: kramdown
permalink: /:categories/:title/
plugins:
  - jekyll-responsive-image
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

feed:
  path: feed.xml

collections:
  gigs:
    output: true
    permalink: /gigs/:path/
  pages:
    output: true
    permalink: /:path/
  stories:
    output: true
    permalink: /posts/:path/

defaults:
  -
    scope:
      path: "" # any file
    values:
      layout: page
  -
    scope:
      type: gigs
    values:
      layout: gig
  -
    scope:
      type: pages
    values:
      layout: page
  -
    scope:
      type: posts
    values:
      layout: story
  


responsive_image:
  # [Required]
  # Path to the image template.
  template: _includes/responsive-image.html

  # [Optional, Default: 85]
  # Quality to use when resizing images.
  default_quality: 90

  # [Optional, Default: []]
  # An array of resize configuration objects. Each object must contain at least
  # a `width` value.
  sizes:
    - width: 255
    - width: 510
    - width: 1020

  # [Optional, Default: false]
  # Rotate resized images depending on their EXIF rotation attribute. Useful for
  # working with JPGs directly from digital cameras and smartphones
  auto_rotate: false

  # [Optional, Default: false]
  # Strip EXIF and other JPEG profiles. Helps to minimize JPEG size and win friends
  # at Google PageSpeed.
  strip: false

  # [Optional, Default: assets]
  # The base directory where assets are stored. This is used to determine the
  # `dirname` value in `output_path_format` below.
  base_path: assets

  # [Optional, Default: assets/resized/%{filename}-%{width}x%{height}.%{extension}]
  # The template used when generating filenames for resized images. Must be a
  # relative path.
  #
  # Parameters available are:
  #   %{dirname}     Directory of the file relative to `base_path` (assets/sub/dir/some-file.jpg => sub/dir)
  #   %{basename}    Basename of the file (assets/some-file.jpg => some-file.jpg)
  #   %{filename}    Basename without the extension (assets/some-file.jpg => some-file)
  #   %{extension}   Extension of the file (assets/some-file.jpg => jpg)
  #   %{width}       Width of the resized image
  #   %{height}      Height of the resized image
  #
  output_path_format: assets/responsive/%{width}/%{basename}

  # [Optional, Default: true]
  # Whether or not to save the generated assets into the source folder.
  save_to_source: false

  # [Optional, Default: false]
  # Cache the result of {% responsive_image %} and {% responsive_image_block %}
  # tags. See the "Caching" section of the README for more information.
  cache: false

  # [Optional, Default: []]
  # By default, only images referenced by the responsive_image and responsive_image_block
  # tags are resized. Here you can set a list of paths or path globs to resize other
  # images. This is useful for resizing images which will be referenced from stylesheets.
  extra_images:
    - assets/foo/bar.png
    - assets/bgs/*.png
    - assets/avatars/*.{jpeg,jpg}
